services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: chenyihang2
      MYSQL_DATABASE: price
    ports:
      - "3308:3306"  # 将容器内的 3306 端口映射到主机的 3309 端口
    volumes:
      - db_data:/var/lib/mysql
    restart: always


  backend:
    build:
      context: ./backend/myproject  # Path to your Django app
      dockerfile: Dockerfile
    volumes:
      - ./backend/myproject:/app  # 将宿主机的 ./backend/myproject/ 目录挂载到容器的 /app 目录
    ports:
      - "8000:8000"  # Expose port for Django  
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:chenyihang2@db:3306/price  # 添加数据库连接 URL
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]


  frontend:
    build:
      context: ./frontend  # Path to your Vue app
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  # Mount your frontend code
    ports:
      - "8080:8080"  # Expose port for Vue
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  db_data: