# 使用官方 Python 镜像
FROM python:3.12

# 设置工作目录
WORKDIR /app


# 安装依赖
RUN apt-get update && apt-get install -y libgl1
RUN apt-get update && apt-get install -y libgl1 unzip
# RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list

# 安装必要的依赖，包括 libglib 和其他缺少的库
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libx11-dev \
    libgdk-pixbuf2.0-dev \
    libgtk-3-0 \
    libnss3 \
    libasound2 \
    libxcomposite1 \
    libxrandr2 \
    libxi6 \
    libxtst6 \
    wget \
    unzip \
    curl \
    ca-certificates \
    gnupg \
    fonts-liberation \
    libdrm2 \
    libgbm1 \
    libvulkan1 \
    xdg-utils \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgles2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrender1 \
    libxss1 \
    lsb-release \
    xdg-utils

# 安装 Microsoft Edge 浏览器
RUN curl https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_131.0.2903.112-1_amd64.deb -o microsoft-edge-stable.deb && \
    dpkg -i microsoft-edge-stable.deb && \
    apt-get update && \
    apt-get -f install && \
    rm microsoft-edge-stable.deb

# 如果需要安装 msedgedriver
RUN wget https://msedgedriver.azureedge.net/131.0.2903.112/edgedriver_linux64.zip && \
    unzip edgedriver_linux64.zip && \
    mv msedgedriver /usr/local/bin/ && \
    rm edgedriver_linux64.zip
# # 下载并安装EdgeDriver
# RUN wget https://msedgedriver.azureedge.net/131.0.2903.112/edgedriver_linux64.zip \
#     && unzip edgedriver_linux64.zip -d /usr/local/bin/ \
#     && chmod +x /usr/local/bin/msedgedriver \
#     && echo "Download successful for EdgeDriver" \
#     && rm edgedriver_linux64.zip
# 复制项目文件到工作目录
COPY . .  
RUN apt-get update
RUN apt-get install -f

# # 在docker中安装edge
# RUN dpkg -i ./microsoft-edge-stable_131.0.2903.112-1_amd64.deb || true 
# RUN apt-get install -fy
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r ./requirements.txt   
RUN pip install pandas




# 启动 Django 服务器
CMD ["python", "./myproject/manage.py", "runserver", "0.0.0.0:8000"]