# 使用官方 Python 镜像
FROM python:3.12

# 设置工作目录
WORKDIR /app


# 安装依赖
RUN apt-get update && apt-get install -y libgl1
RUN apt-get update && apt-get install -y libgl1 unzip
# 安装Microsoft Edge
# RUN wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_109.0.1518.61-1_amd64.deb \
#     && dpkg -i microsoft-edge-stable_109.0.1518.61-1_amd64.deb \
#     && rm microsoft-edge-stable_109.0.1518.61-1_amd64.deb

# 确保Microsoft Edge的可执行文件在PATH环境变量中
# RUN ln -s /opt/microsoft/edge/edge /usr/bin/msedge
# # 下载并安装EdgeDriver
# RUN wget https://msedgedriver.azureedge.net/132.0.2957.48/edgedriver_linux64.zip \
#     && unzip edgedriver_linux64.zip -d /usr/local/bin/ \
#     && chmod +x /usr/local/bin/msedgedriver \
#     && echo "Download successful for EdgeDriver" \
#     && rm edgedriver_linux64.zip
# 复制项目文件到工作目录
COPY . .  
RUN apt-get update
RUN apt-get install -f
RUN dpkg -i ./microsoft-edge-stable_131.0.2903.112-1_amd64.deb || true
RUN apt-get install -fy
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r ./requirements.txt   
RUN pip install pandas



# 运行迁移
# RUN python ./myproject/manage.py makemigrations
# RUN python ./myproject/manage.py migrate
# RUN python ./myproject/manage.py runserver

# 启动 Django 服务器
CMD ["python", "./myproject/manage.py", "runserver", "0.0.0.0:8000"]